spring:
    application:
        name: userservice
    datasource:
        url: jdbc:postgresql://localhost:5432/fitness-micro-user
        username: postgres
        password: admin@123
    
    jpa:
        hibernate:
            # ddl-auto: update
            ddl-auto: create
        database-platform: org.hibernate.dialect.PostgreSQLDialect
